#ifndef __BSP_IWDG_H
#define __BSP_IWDG_H

#include "GlobalDef.h"

enum
{
	E_WDGT_FLAG_SSTATETASK = 0,
	E_WDGT_FLAG_SSTATISTICTASK,  
	E_WDGT_FLAG_SPROTECTTASK,
	E_WDGT_FLAG_SRUNMODECTRLTASK,
	E_WDGT_FLAG_SRAPIDDEALTASK,  
	E_WDGT_FLAG_SFUNCTASK,
	E_WDGT_FLAG_STASKSYSCYCLE,  
	E_WDGT_FLAG_MODBUSTASK,
	E_WDGT_FLAG_MODPROBLETASK, 
	E_WDGT_FLAG_SBMSTASK,    
	E_WDGT_FLAG_XFANTIMER,
	E_WDGT_FLAG_MAX
};



void sIWDG_Init(void);
void sIWDG_Feed(uint8_t Flag);


#endif
